import os
from pathlib import Path
import shutil

from src.preprocess import NetworkDataPreprocessor


def test_preprocess_creates_processed_csv(tmp_path):
    # Arrange: ensure output directory under repo structure
    project_root = Path(__file__).resolve().parents[1]
    data_raw = project_root / "data" / "raw"
    data_processed = project_root / "data" / "processed"
    data_raw.mkdir(parents=True, exist_ok=True)
    data_processed.mkdir(parents=True, exist_ok=True)

    input_csv = data_raw / "sample.csv"  # generator will create if missing
    output_csv = data_processed / "processed.csv"

    # Act: run preprocess on synthetic/autogenerated data
    pre = NetworkDataPreprocessor(use_pca=False)
    pre.preprocess(str(input_csv), str(output_csv), dry_run=False)

    # Assert: processed file exists and is non-empty
    assert output_csv.exists(), "processed.csv was not created"
    assert output_csv.stat().st_size > 0, "processed.csv is empty"

